// 자주 쓰는 단부루 태그의 한글 이름. API 키 없이도 한글로 태그를 찾고, 영어 태그 옆에 뜻을 보여주는 데 쓴다.
// 형식: [태그, [표시용 한글 이름, 그 밖의 검색어...]]. 태그는 앱의 태그 색인(src/assets/tags.json)에
// 실제로 있는 것만 넣는다 — `npm run check:ko-tags`가 검사한다.
export const KO_TAG_GLOSSARY: ReadonlyArray<readonly [string, readonly string[]]> = [
    ["1girl", ["소녀 1명", "여자 1명", "여자", "소녀", "여캐"]],
    ["2girls", ["소녀 2명", "여자 2명"]],
    ["3girls", ["소녀 3명", "여자 3명"]],
    ["multiple girls", ["여러 소녀", "여자 여러명"]],
    ["1boy", ["소년 1명", "남자 1명", "남자", "소년", "남캐"]],
    ["2boys", ["소년 2명", "남자 2명"]],
    ["multiple boys", ["여러 소년", "남자 여러명"]],
    ["solo", ["혼자", "단독", "솔로"]],
    ["couple", ["커플", "연인"]],
    ["no humans", ["사람 없음", "인물 없음"]],
    ["long hair", ["긴 머리", "장발", "긴머리"]],
    ["short hair", ["짧은 머리", "단발", "짧은머리"]],
    ["very long hair", ["아주 긴 머리", "매우 긴 머리"]],
    ["medium hair", ["중간 길이 머리", "중단발"]],
    ["bob cut", ["단발머리", "보브컷", "밥컷"]],
    ["ponytail", ["포니테일", "묶은 머리", "말총머리"]],
    ["twintails", ["트윈테일", "양갈래"]],
    ["side ponytail", ["사이드 포니테일"]],
    ["high ponytail", ["하이 포니테일", "높게 묶은 머리"]],
    ["low ponytail", ["로우 포니테일", "낮게 묶은 머리"]],
    ["braid", ["땋은 머리", "브레이드"]],
    ["twin braids", ["양갈래 땋은 머리", "트윈 브레이드"]],
    ["single braid", ["한 갈래 땋은 머리"]],
    ["hair bun", ["올림머리", "번헤어", "똥머리"]],
    ["double bun", ["양쪽 올림머리", "더블 번", "만두머리"]],
    ["ahoge", ["아호게", "바보털"]],
    ["blunt bangs", ["일자 앞머리", "뱅헤어"]],
    ["parted bangs", ["가르마 앞머리", "갈라진 앞머리"]],
    ["swept bangs", ["넘긴 앞머리"]],
    ["hair between eyes", ["눈 사이 머리카락"]],
    ["hair over one eye", ["한쪽 눈을 가린 머리"]],
    ["sidelocks", ["옆머리"]],
    ["wavy hair", ["웨이브 머리", "물결 머리"]],
    ["curly hair", ["곱슬머리"]],
    ["straight hair", ["생머리", "직모"]],
    ["messy hair", ["헝클어진 머리", "부스스한 머리"]],
    ["wet hair", ["젖은 머리"]],
    ["floating hair", ["흩날리는 머리", "날리는 머리"]],
    ["hair down", ["풀어헤친 머리", "푼 머리"]],
    ["black hair", ["검은 머리", "흑발"]],
    ["blonde hair", ["금발", "노란 머리"]],
    ["brown hair", ["갈색 머리", "갈발"]],
    ["white hair", ["흰 머리", "백발"]],
    ["grey hair", ["회색 머리", "은회색 머리"]],
    ["silver hair", ["은발", "은색 머리"]],
    ["red hair", ["빨간 머리", "적발"]],
    ["blue hair", ["파란 머리", "청발"]],
    ["pink hair", ["분홍 머리", "핑크 머리"]],
    ["purple hair", ["보라색 머리", "자발"]],
    ["green hair", ["초록 머리", "녹발"]],
    ["orange hair", ["주황 머리"]],
    ["aqua hair", ["청록색 머리", "민트색 머리"]],
    ["light brown hair", ["밝은 갈색 머리"]],
    ["multicolored hair", ["여러 색 머리", "투톤 머리"]],
    ["gradient hair", ["그라데이션 머리"]],
    ["streaked hair", ["브릿지 머리", "부분 염색"]],
    ["two-tone hair", ["투톤 머리"]],
    ["blue eyes", ["파란 눈", "벽안"]],
    ["red eyes", ["빨간 눈", "적안"]],
    ["green eyes", ["초록 눈", "녹안"]],
    ["brown eyes", ["갈색 눈"]],
    ["purple eyes", ["보라색 눈", "자안"]],
    ["yellow eyes", ["노란 눈", "금안"]],
    ["pink eyes", ["분홍 눈"]],
    ["black eyes", ["검은 눈", "흑안"]],
    ["grey eyes", ["회색 눈"]],
    ["aqua eyes", ["청록색 눈"]],
    ["orange eyes", ["주황 눈"]],
    ["heterochromia", ["오드아이", "짝눈"]],
    ["closed eyes", ["감은 눈", "눈 감음"]],
    ["one eye closed", ["윙크", "한쪽 눈 감음"]],
    ["half-closed eyes", ["반쯤 감은 눈", "게슴츠레한 눈"]],
    ["tsurime", ["올라간 눈매", "츠리메"]],
    ["tareme", ["처진 눈매", "타레메"]],
    ["long eyelashes", ["긴 속눈썹"]],
    ["glowing eyes", ["빛나는 눈"]],
    ["smile", ["미소", "웃음", "웃는 얼굴"]],
    ["grin", ["활짝 웃음", "씩 웃음"]],
    ["light smile", ["옅은 미소", "가벼운 미소"]],
    ["smirk", ["비웃음", "능글맞은 미소"]],
    ["laughing", ["웃는 중", "폭소"]],
    ["open mouth", ["입 벌림", "벌린 입"]],
    ["closed mouth", ["다문 입", "입 다뭄"]],
    ["blush", ["홍조", "볼 빨개짐", "부끄러움"]],
    ["crying", ["우는 중", "울음"]],
    ["tears", ["눈물"]],
    ["angry", ["화남", "분노"]],
    ["sad", ["슬픔", "슬픈 표정"]],
    ["surprised", ["놀람", "놀란 표정"]],
    ["embarrassed", ["당황", "민망함"]],
    ["expressionless", ["무표정"]],
    ["serious", ["진지함", "진지한 표정"]],
    ["frown", ["찡그림", "찌푸림"]],
    ["pout", ["삐침", "뾰로통"]],
    ["sleepy", ["졸림", "졸린 표정"]],
    ["scared", ["겁먹음", "무서워함"]],
    ["happy", ["행복", "기쁨"]],
    ["shy", ["수줍음"]],
    ["tongue out", ["혀 내밀기", "메롱"]],
    ["fang", ["송곳니", "덧니"]],
    ["sweat", ["땀"]],
    ["looking at viewer", ["정면 응시", "카메라 응시", "시선 맞춤"]],
    ["looking away", ["시선 회피", "다른 곳을 봄"]],
    ["looking back", ["뒤돌아봄"]],
    ["looking down", ["아래를 봄"]],
    ["looking up", ["위를 봄"]],
    ["looking to the side", ["옆을 봄"]],
    ["standing", ["서 있음", "서있는"]],
    ["sitting", ["앉아 있음", "앉은"]],
    ["lying", ["누워 있음", "누운"]],
    ["on back", ["바로 누움", "등을 대고 누움"]],
    ["on stomach", ["엎드림"]],
    ["on side", ["옆으로 누움"]],
    ["kneeling", ["무릎 꿇음"]],
    ["squatting", ["쪼그려 앉음"]],
    ["walking", ["걷는 중", "걷기"]],
    ["running", ["달리는 중", "달리기"]],
    ["jumping", ["점프", "뛰어오름"]],
    ["dancing", ["춤", "춤추는 중"]],
    ["sleeping", ["자는 중", "잠"]],
    ["leaning forward", ["앞으로 숙임"]],
    ["arms up", ["양팔 올림", "만세"]],
    ["arm up", ["한 팔 올림"]],
    ["arms behind back", ["뒷짐", "팔을 뒤로"]],
    ["crossed arms", ["팔짱"]],
    ["hand on own hip", ["허리에 손"]],
    ["hands on own hips", ["양손 허리에"]],
    ["hand up", ["한 손 올림"]],
    ["waving", ["손 흔들기"]],
    ["v", ["브이", "피스 사인"]],
    ["pointing", ["가리키기"]],
    ["outstretched arms", ["팔 벌림"]],
    ["holding hands", ["손 잡기"]],
    ["hug", ["포옹", "껴안기"]],
    ["kiss", ["키스", "입맞춤"]],
    ["head tilt", ["고개 기울임", "갸웃"]],
    ["crossed legs", ["다리 꼼"]],
    ["wariza", ["오리 앉기", "W 앉기"]],
    ["seiza", ["정좌", "무릎 꿇고 앉기"]],
    ["indian style", ["책상다리", "아빠다리"]],
    ["stretching", ["기지개", "스트레칭"]],
    ["holding", ["들고 있음", "쥐고 있음"]],
    ["reading", ["독서", "책 읽기"]],
    ["eating", ["먹는 중", "식사"]],
    ["drinking", ["마시는 중"]],
    ["cooking", ["요리"]],
    ["singing", ["노래"]],
    ["fighting stance", ["전투 자세"]],
    ["school uniform", ["교복"]],
    ["serafuku", ["세일러복", "세라복"]],
    ["sailor collar", ["세일러 칼라"]],
    ["shirt", ["셔츠"]],
    ["white shirt", ["흰 셔츠"]],
    ["t-shirt", ["티셔츠"]],
    ["blouse", ["블라우스"]],
    ["sweater", ["스웨터", "니트"]],
    ["hoodie", ["후드티", "후디"]],
    ["jacket", ["재킷", "자켓"]],
    ["coat", ["코트"]],
    ["cardigan", ["가디건"]],
    ["vest", ["조끼"]],
    ["dress", ["드레스", "원피스"]],
    ["white dress", ["흰 원피스", "하얀 드레스"]],
    ["black dress", ["검은 드레스"]],
    ["sundress", ["선드레스", "여름 원피스"]],
    ["wedding dress", ["웨딩드레스"]],
    ["skirt", ["치마", "스커트"]],
    ["pleated skirt", ["주름 치마", "플리츠 스커트"]],
    ["miniskirt", ["미니스커트", "짧은 치마"]],
    ["long skirt", ["긴 치마", "롱스커트"]],
    ["pants", ["바지"]],
    ["shorts", ["반바지", "쇼츠"]],
    ["jeans", ["청바지"]],
    ["suit", ["정장", "양복"]],
    ["necktie", ["넥타이"]],
    ["bowtie", ["나비넥타이"]],
    ["ribbon", ["리본"]],
    ["bow", ["리본 장식", "보우"]],
    ["scarf", ["목도리", "스카프"]],
    ["gloves", ["장갑"]],
    ["thighhighs", ["허벅지 스타킹", "니삭스", "오버니"]],
    ["pantyhose", ["팬티스타킹", "스타킹"]],
    ["socks", ["양말"]],
    ["kneehighs", ["무릎 양말", "니하이삭스"]],
    ["shoes", ["신발"]],
    ["boots", ["부츠"]],
    ["sneakers", ["운동화"]],
    ["high heels", ["하이힐"]],
    ["loafers", ["로퍼"]],
    ["sandals", ["샌들"]],
    ["barefoot", ["맨발"]],
    ["hat", ["모자"]],
    ["beret", ["베레모"]],
    ["witch hat", ["마녀 모자"]],
    ["straw hat", ["밀짚모자"]],
    ["baseball cap", ["야구 모자", "캡 모자"]],
    ["hood", ["후드"]],
    ["glasses", ["안경"]],
    ["sunglasses", ["선글라스"]],
    ["hair ornament", ["머리 장식"]],
    ["hair ribbon", ["머리 리본"]],
    ["hair bow", ["머리 리본 장식"]],
    ["hairband", ["머리띠"]],
    ["hairclip", ["머리핀", "헤어핀"]],
    ["hair flower", ["머리 꽃 장식"]],
    ["earrings", ["귀걸이"]],
    ["necklace", ["목걸이"]],
    ["choker", ["초커"]],
    ["bracelet", ["팔찌"]],
    ["ring", ["반지"]],
    ["jewelry", ["장신구", "보석"]],
    ["crown", ["왕관"]],
    ["tiara", ["티아라"]],
    ["mask", ["마스크", "가면"]],
    ["headphones", ["헤드폰"]],
    ["bag", ["가방"]],
    ["backpack", ["백팩", "책가방"]],
    ["kimono", ["기모노"]],
    ["yukata", ["유카타"]],
    ["hanbok", ["한복"]],
    ["maid", ["메이드"]],
    ["maid headdress", ["메이드 머리 장식"]],
    ["apron", ["앞치마"]],
    ["nurse", ["간호사"]],
    ["armor", ["갑옷"]],
    ["cape", ["망토"]],
    ["swimsuit", ["수영복"]],
    ["pajamas", ["잠옷", "파자마"]],
    ["gym uniform", ["체육복"]],
    ["military uniform", ["군복"]],
    ["japanese clothes", ["일본 전통 의상", "일본 옷"]],
    ["chinese clothes", ["중국 전통 의상", "중국 옷"]],
    ["long sleeves", ["긴 소매", "긴팔"]],
    ["short sleeves", ["짧은 소매", "반팔"]],
    ["sleeveless", ["민소매"]],
    ["bare shoulders", ["드러난 어깨", "어깨 노출"]],
    ["off shoulder", ["오프숄더"]],
    ["collared shirt", ["칼라 셔츠", "깃 있는 셔츠"]],
    ["frills", ["프릴", "레이스 주름"]],
    ["lace", ["레이스"]],
    ["animal ears", ["동물 귀"]],
    ["cat ears", ["고양이 귀", "네코미미"]],
    ["fox ears", ["여우 귀"]],
    ["rabbit ears", ["토끼 귀"]],
    ["dog ears", ["강아지 귀", "개 귀"]],
    ["wolf ears", ["늑대 귀"]],
    ["tail", ["꼬리"]],
    ["cat tail", ["고양이 꼬리"]],
    ["fox tail", ["여우 꼬리"]],
    ["wings", ["날개"]],
    ["angel wings", ["천사 날개"]],
    ["horns", ["뿔"]],
    ["halo", ["헤일로", "천사 고리"]],
    ["pointy ears", ["뾰족 귀", "엘프 귀"]],
    ["elf", ["엘프"]],
    ["angel", ["천사"]],
    ["demon girl", ["악마 소녀"]],
    ["vampire", ["뱀파이어", "흡혈귀"]],
    ["witch", ["마녀"]],
    ["mermaid", ["인어"]],
    ["fairy", ["요정"]],
    ["robot", ["로봇"]],
    ["cat", ["고양이"]],
    ["dog", ["강아지", "개"]],
    ["bird", ["새"]],
    ["rabbit", ["토끼"]],
    ["butterfly", ["나비"]],
    ["fish", ["물고기"]],
    ["dragon", ["드래곤", "용"]],
    ["horse", ["말"]],
    ["outdoors", ["야외", "실외"]],
    ["indoors", ["실내"]],
    ["sky", ["하늘"]],
    ["blue sky", ["파란 하늘", "푸른 하늘"]],
    ["cloud", ["구름"]],
    ["cloudy sky", ["흐린 하늘"]],
    ["night", ["밤"]],
    ["night sky", ["밤하늘"]],
    ["star (sky)", ["별 (하늘)", "별"]],
    ["starry sky", ["별이 빛나는 하늘", "별하늘"]],
    ["moon", ["달"]],
    ["full moon", ["보름달"]],
    ["crescent moon", ["초승달"]],
    ["sun", ["태양", "해"]],
    ["sunset", ["노을", "일몰", "석양"]],
    ["sunrise", ["일출", "해돋이"]],
    ["day", ["낮"]],
    ["evening", ["저녁"]],
    ["twilight", ["황혼", "해질녘"]],
    ["rain", ["비"]],
    ["snow", ["눈 (날씨)", "눈 내림"]],
    ["snowing", ["눈 내리는 중"]],
    ["wind", ["바람"]],
    ["fog", ["안개"]],
    ["rainbow", ["무지개"]],
    ["lightning", ["번개"]],
    ["ocean", ["바다"]],
    ["beach", ["해변", "바닷가"]],
    ["water", ["물"]],
    ["river", ["강"]],
    ["lake", ["호수"]],
    ["waterfall", ["폭포"]],
    ["mountain", ["산"]],
    ["forest", ["숲"]],
    ["tree", ["나무"]],
    ["grass", ["풀", "잔디"]],
    ["flower", ["꽃"]],
    ["rose", ["장미"]],
    ["cherry blossoms", ["벚꽃"]],
    ["sunflower", ["해바라기"]],
    ["field", ["들판"]],
    ["flower field", ["꽃밭"]],
    ["garden", ["정원"]],
    ["park", ["공원"]],
    ["city", ["도시"]],
    ["cityscape", ["도시 풍경"]],
    ["street", ["거리", "길거리"]],
    ["building", ["건물"]],
    ["house", ["집"]],
    ["school", ["학교"]],
    ["classroom", ["교실"]],
    ["library", ["도서관"]],
    ["cafe", ["카페"]],
    ["restaurant", ["식당", "레스토랑"]],
    ["kitchen", ["부엌", "주방"]],
    ["bedroom", ["침실"]],
    ["bathroom", ["욕실", "화장실"]],
    ["living room", ["거실"]],
    ["office", ["사무실"]],
    ["hospital", ["병원"]],
    ["church", ["교회", "성당"]],
    ["shrine", ["신사"]],
    ["castle", ["성"]],
    ["bridge", ["다리 (건축물)", "다리"]],
    ["train", ["기차", "열차"]],
    ["train station", ["기차역"]],
    ["rooftop", ["옥상"]],
    ["window", ["창문"]],
    ["door", ["문"]],
    ["bed", ["침대"]],
    ["chair", ["의자"]],
    ["couch", ["소파"]],
    ["table", ["테이블", "탁자"]],
    ["desk", ["책상"]],
    ["book", ["책"]],
    ["bookshelf", ["책장"]],
    ["umbrella", ["우산"]],
    ["sword", ["검", "칼"]],
    ["katana", ["카타나", "일본도"]],
    ["gun", ["총"]],
    ["bow (weapon)", ["활"]],
    ["staff", ["지팡이", "스태프"]],
    ["shield", ["방패"]],
    ["guitar", ["기타"]],
    ["piano", ["피아노"]],
    ["microphone", ["마이크"]],
    ["phone", ["전화기", "휴대폰"]],
    ["smartphone", ["스마트폰"]],
    ["camera", ["카메라"]],
    ["cup", ["컵"]],
    ["teacup", ["찻잔"]],
    ["food", ["음식"]],
    ["cake", ["케이크"]],
    ["fruit", ["과일"]],
    ["ice cream", ["아이스크림"]],
    ["bread", ["빵"]],
    ["coffee", ["커피"]],
    ["tea", ["차 (음료)", "차"]],
    ["candy", ["사탕"]],
    ["balloon", ["풍선"]],
    ["lantern", ["등불", "랜턴"]],
    ["candle", ["양초", "촛불"]],
    ["fire", ["불", "화염"]],
    ["smoke", ["연기"]],
    ["bubble", ["비눗방울", "거품"]],
    ["petals", ["꽃잎"]],
    ["falling petals", ["떨어지는 꽃잎", "흩날리는 꽃잎"]],
    ["leaf", ["나뭇잎", "잎"]],
    ["autumn leaves", ["단풍", "가을 잎"]],
    ["snowflakes", ["눈송이"]],
    ["sparkle", ["반짝임", "반짝이"]],
    ["light particles", ["빛 입자"]],
    ["lens flare", ["렌즈 플레어"]],
    ["sunlight", ["햇빛", "햇살"]],
    ["moonlight", ["달빛"]],
    ["backlighting", ["역광"]],
    ["light rays", ["빛줄기", "빛내림"]],
    ["shadow", ["그림자"]],
    ["silhouette", ["실루엣"]],
    ["reflection", ["반사", "비친 모습"]],
    ["depth of field", ["피사계 심도", "아웃포커싱"]],
    ["blurry background", ["흐린 배경", "배경 흐림"]],
    ["simple background", ["단순한 배경"]],
    ["white background", ["흰 배경"]],
    ["black background", ["검은 배경"]],
    ["grey background", ["회색 배경"]],
    ["gradient background", ["그라데이션 배경"]],
    ["transparent background", ["투명 배경"]],
    ["scenery", ["풍경"]],
    ["landscape", ["풍경화", "경치"]],
    ["portrait", ["초상", "인물 클로즈업"]],
    ["upper body", ["상반신"]],
    ["full body", ["전신"]],
    ["cowboy shot", ["무릎 위 샷", "카우보이 샷"]],
    ["close-up", ["클로즈업", "근접"]],
    ["from above", ["위에서 본 구도", "부감"]],
    ["from below", ["아래에서 본 구도", "앙각"]],
    ["from side", ["옆에서 본 구도", "측면"]],
    ["from behind", ["뒤에서 본 구도", "뒷모습"]],
    ["profile", ["옆모습", "옆얼굴"]],
    ["dutch angle", ["기울어진 구도", "더치 앵글"]],
    ["wide shot", ["와이드 샷", "넓은 구도"]],
    ["pov", ["1인칭 시점"]],
    ["monochrome", ["흑백", "모노크롬"]],
    ["greyscale", ["그레이스케일", "회색조"]],
    ["sketch", ["스케치"]],
    ["watercolor (medium)", ["수채화"]],
    ["chibi", ["치비", "SD 캐릭터", "미니 캐릭터"]],
    ["pixel art", ["픽셀 아트", "도트"]],
    ["spring (season)", ["봄"]],
    ["summer", ["여름"]],
    ["autumn", ["가을"]],
    ["winter", ["겨울"]],
    ["christmas", ["크리스마스"]],
    ["halloween", ["할로윈"]],
    ["festival", ["축제"]],
    ["fireworks", ["불꽃놀이"]],
    ["magic", ["마법"]],
    ["fantasy", ["판타지"]],
    ["science fiction", ["공상과학", "SF"]],
    ["cyberpunk", ["사이버펑크"]],
    ["steampunk", ["스팀펑크"]],
    ["ruins", ["폐허", "유적"]],
    ["space", ["우주"]],
    ["underwater", ["물속", "수중"]],
]
