/**
 * NAI Image Metadata Parser
 *
 * NovelAI embeds metadata in PNG images via:
 * 1. Standard PNG tEXt chunks (Comment field with JSON)
 * 2. Stealth PNGInfo in alpha channel (for persistence through SNS)
 *
 * This parser extracts metadata from both sources.
 */

import { readNais2Params, type Nais2GenerationSources } from '@/lib/nais2-png-meta'
import {
    AVAILABLE_MODELS,
    getModelCapabilities,
    type QualityTagPresetId,
} from '@/lib/model-capabilities'

/**
 * Decompress gzip data using native Web API or fallback
 */
async function decompressGzip(data: Uint8Array): Promise<string> {
    try {
        // Try native DecompressionStream (modern browsers)
        if (typeof DecompressionStream !== 'undefined') {
            const stream = new DecompressionStream('gzip')
            const writer = stream.writable.getWriter()
            writer.write(new Uint8Array(data.buffer as ArrayBuffer, data.byteOffset, data.byteLength))
            writer.close()

            const reader = stream.readable.getReader()
            const chunks: Uint8Array[] = []

            while (true) {
                const { done, value } = await reader.read()
                if (done) break
                chunks.push(value)
            }

            const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0)
            const result = new Uint8Array(totalLength)
            let offset = 0
            for (const chunk of chunks) {
                result.set(chunk, offset)
                offset += chunk.length
            }

            return new TextDecoder('utf-8').decode(result)
        }
    } catch (e) {
        console.log('Native decompression failed, trying pako fallback:', e)
    }

    // Fallback to pako if available
    try {
        const pako = await import('pako')
        return pako.ungzip(data, { to: 'string' })
    } catch (e) {
        console.error('Gzip decompression failed:', e)
        throw new Error('Failed to decompress gzip data')
    }
}

export interface NAIMetadata {
    // Basic params
    prompt?: string
    negativePrompt?: string  // "uc" in NAI format

    // Generation settings
    model?: string  // Extracted from "Source" PNG tEXt chunk
    modelId?: string // Forge model ID resolved from Source
    steps?: number
    cfgScale?: number  // "scale" in NAI
    cfgRescale?: number
    seed?: number
    sampler?: string
    scheduler?: string  // "noise_schedule" in NAI

    // SMEA
    smea?: boolean  // "sm" in NAI
    smeaDyn?: boolean  // "sm_dyn" in NAI
    variety?: boolean // Derived from "skip_cfg_above_sigma"
    qualityToggle?: boolean // "qualityToggle" - Add Quality Tags
    qualityTagPreset?: QualityTagPresetId
    ucPreset?: number // "ucPreset" - Undesired Content Preset (0=Heavy, 1=Light, 2=Furry, 3=Human, 4=None)
    transparentBackground?: boolean

    // Resolution
    width?: number
    height?: number

    // V4 specific
    v4_prompt?: {
        caption?: {
            base_caption?: string
            char_captions?: Array<{
                char_caption: string
                centers: Array<{ x: number, y: number }>
            }>
        }
    }
    v4_negative_prompt?: {
        caption?: {
            base_caption?: string
            char_captions?: Array<{
                char_caption: string
                centers: Array<{ x: number, y: number }>
            }>
        }
    }

    // Reference images (metadata only, not actual images)
    hasVibeTransfer?: boolean
    hasCharacterReference?: boolean

    // Vibe Transfer details (strength, info_extracted per image)
    vibeTransferInfo?: Array<{
        strength: number
        informationExtracted: number
    }>

    // Pre-encoded vibe data (for reuse without re-encoding)
    encodedVibes?: string[]

    // Character Reference details
    characterReferenceInfo?: Array<{
        strength: number
        informationExtracted: number
    }>

    // Source info
    source?: 'text_chunk' | 'stealth_alpha'

    // Raw data for debugging
    raw?: Record<string, unknown>

    // Original NAIS2 prompt sections (populated only when the image was
    // generated by NAIS2 and contains a nais2-params chunk with promptParts).
    promptParts?: {
        base: string
        additional: string
        detail: string
        negative?: string
        inpainting?: string
    }

    // Active Forge-local sources, used to restore existing character and
    // reference entries without embedding original image data.
    generationSources?: Nais2GenerationSources
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null
}

function isFiniteNumber(value: unknown): value is number {
    return typeof value === 'number' && Number.isFinite(value)
}

function parseGenerationSources(value: unknown): Nais2GenerationSources | undefined {
    if (!isRecord(value)
        || !Array.isArray(value.characterPrompts)
        || !Array.isArray(value.characterReferences)
        || !Array.isArray(value.vibeReferences)
    ) return undefined

    const characterPrompts = value.characterPrompts.flatMap((entry) => {
        if (!isRecord(entry) || typeof entry.id !== 'string' || typeof entry.prompt !== 'string'
            || typeof entry.negative !== 'string' || !isRecord(entry.position)
            || !isFiniteNumber(entry.position.x) || !isFiniteNumber(entry.position.y)
        ) return []

        return [{
            id: entry.id,
            presetId: typeof entry.presetId === 'string' ? entry.presetId : undefined,
            name: typeof entry.name === 'string' ? entry.name : undefined,
            prompt: entry.prompt,
            negative: entry.negative,
            promptEnabled: typeof entry.promptEnabled === 'boolean' ? entry.promptEnabled : undefined,
            negativeEnabled: typeof entry.negativeEnabled === 'boolean' ? entry.negativeEnabled : undefined,
            costumeEnabled: typeof entry.costumeEnabled === 'boolean' ? entry.costumeEnabled : undefined,
            position: { x: entry.position.x, y: entry.position.y },
        }]
    })

    const parseReferences = (entries: unknown[]): Nais2GenerationSources['characterReferences'] => entries.flatMap((entry) => {
        if (!isRecord(entry) || typeof entry.id !== 'string'
            || !isFiniteNumber(entry.informationExtracted)
            || !isFiniteNumber(entry.strength)
            || !isFiniteNumber(entry.fidelity)
            || (entry.referenceType !== 'character' && entry.referenceType !== 'style' && entry.referenceType !== 'character&style')
        ) return []

        return [{
            id: entry.id,
            name: typeof entry.name === 'string' ? entry.name : undefined,
            informationExtracted: entry.informationExtracted,
            strength: entry.strength,
            fidelity: entry.fidelity,
            referenceType: entry.referenceType,
        }]
    })

    return {
        characterPrompts,
        characterReferences: parseReferences(value.characterReferences),
        vibeReferences: parseReferences(value.vibeReferences),
        characterPositionEnabled: value.characterPositionEnabled === true,
    }
}



/**
 * Extract metadata from alpha channel (stealth_pnginfo)
 * This method works even after images are uploaded to SNS
 * Ported from legacy Python stealth_png_reader.py
 */
async function extractStealthMetadata(imageData: ImageData): Promise<NAIMetadata | null> {
    try {
        const { data, width, height } = imageData
        const SIGNATURES = {
            alpha: {
                uncompressed: 'stealth_pnginfo',
                compressed: 'stealth_pngcomp'
            }
        }

        // Get pixel data - data is in RGBA order, row by row
        const getPixel = (x: number, y: number) => {
            const i = (y * width + x) * 4
            return {
                r: data[i],
                g: data[i + 1],
                b: data[i + 2],
                a: data[i + 3]
            }
        }

        const sigLen = SIGNATURES.alpha.uncompressed.length * 8 // bits
        let bufferA = ""
        let indexA = 0
        let sigConfirmed = false
        let confirmingSignature = true
        let readingParamLen = false
        let readingParam = false
        let readEnd = false
        let paramLen = 0
        let binaryData = ""
        let compressed = false

        // Column-major traversal - x first, then y (like legacy code)
        for (let x = 0; x < width && !readEnd; x++) {
            for (let y = 0; y < height && !readEnd; y++) {
                const pixel = getPixel(x, y)

                // Read LSB from alpha channel
                bufferA += (pixel.a & 1).toString()
                indexA++

                if (confirmingSignature) {
                    if (indexA === sigLen) {
                        // Convert binary string to text
                        const sig = binaryToString(bufferA)
                        if (sig === SIGNATURES.alpha.uncompressed) {
                            confirmingSignature = false
                            sigConfirmed = true
                            readingParamLen = true
                            compressed = false
                            bufferA = ""
                            indexA = 0
                        } else if (sig === SIGNATURES.alpha.compressed) {
                            confirmingSignature = false
                            sigConfirmed = true
                            readingParamLen = true
                            compressed = true
                            bufferA = ""
                            indexA = 0
                        } else {
                            readEnd = true
                            break
                        }
                    }
                } else if (readingParamLen) {
                    if (indexA === 32) {
                        paramLen = parseInt(bufferA, 2)
                        readingParamLen = false
                        readingParam = true
                        bufferA = ""
                        indexA = 0
                    }
                } else if (readingParam) {
                    if (indexA === paramLen) {
                        binaryData = bufferA
                        readEnd = true
                        break
                    }
                }
            }
        }

        if (!sigConfirmed || binaryData.length === 0) {
            return null
        }

        // Convert binary string to bytes
        const byteData = binaryToBytes(binaryData)

        // Decompress if needed
        let jsonString: string
        if (compressed) {
            jsonString = await decompressGzip(byteData)
        } else {
            jsonString = new TextDecoder('utf-8').decode(byteData)
        }

        // Parse JSON
        let jsonData = JSON.parse(jsonString)

        // Handle nested Comment field
        if (jsonData.Comment && typeof jsonData.Comment === 'string') {
            try {
                jsonData.Comment = JSON.parse(jsonData.Comment)
            } catch { /* ignore */ }
        }

        // Convert to our format - the main data is often in jsonData.Comment
        const sourceData = jsonData.Comment || jsonData
        const metadata = convertNAIFormat(sourceData)
        metadata.source = 'stealth_alpha'
        if (typeof jsonData.Source === 'string') metadata.model = jsonData.Source
        applyModelMetadata(metadata)

        return metadata
    } catch (error) {
        console.log('Stealth metadata extraction failed:', error)
        return null
    }
}

/**
 * Convert binary string to text
 */
function binaryToString(binStr: string): string {
    const bytes: number[] = []
    for (let i = 0; i < binStr.length; i += 8) {
        const byte = binStr.slice(i, i + 8)
        if (byte.length === 8) {
            bytes.push(parseInt(byte, 2))
        }
    }
    return new TextDecoder('utf-8').decode(new Uint8Array(bytes))
}

/**
 * Convert binary string to Uint8Array
 */
function binaryToBytes(binStr: string): Uint8Array {
    const bytes: number[] = []
    for (let i = 0; i < binStr.length; i += 8) {
        const byte = binStr.slice(i, i + 8)
        if (byte.length === 8) {
            bytes.push(parseInt(byte, 2))
        }
    }
    return new Uint8Array(bytes)
}

/**
 * Detect image MIME type from bytes
 */
function detectImageType(bytes: Uint8Array): string {
    // PNG: 89 50 4E 47 0D 0A 1A 0A
    if (bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4E && bytes[3] === 0x47) {
        return 'image/png'
    }
    // WebP: RIFF....WEBP
    if (bytes[0] === 0x52 && bytes[1] === 0x49 && bytes[2] === 0x46 && bytes[3] === 0x46 &&
        bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50) {
        return 'image/webp'
    }
    // JPEG: FF D8 FF
    if (bytes[0] === 0xFF && bytes[1] === 0xD8 && bytes[2] === 0xFF) {
        return 'image/jpeg'
    }
    // Default to PNG
    return 'image/png'
}

/**
 * Load image and get ImageData using Canvas API
 * Supports PNG, WebP, JPEG
 */
async function getImageData(imageBytes: Uint8Array): Promise<ImageData | null> {
    return new Promise((resolve) => {
        const mimeType = detectImageType(imageBytes)
        const blob = new Blob([new Uint8Array(imageBytes.buffer as ArrayBuffer, imageBytes.byteOffset, imageBytes.byteLength)], { type: mimeType })
        const url = URL.createObjectURL(blob)
        const img = new Image()

        img.onload = () => {
            let canvas: HTMLCanvasElement | null = document.createElement('canvas')
            canvas.width = img.width
            canvas.height = img.height
            const ctx = canvas.getContext('2d')

            if (!ctx) {
                URL.revokeObjectURL(url)
                img.src = '' // Clear image reference
                canvas.width = 0 // Release canvas memory
                canvas.height = 0
                resolve(null)
                return
            }

            ctx.drawImage(img, 0, 0)
            const imageData = ctx.getImageData(0, 0, img.width, img.height)
            
            // CRITICAL: Release resources to prevent OOM
            URL.revokeObjectURL(url)
            img.src = ''
            canvas.width = 0
            canvas.height = 0
            canvas = null
            
            resolve(imageData)
        }

        img.onerror = () => {
            URL.revokeObjectURL(url)
            img.src = ''
            resolve(null)
        }

        img.src = url
    })
}

/**
 * Parse image metadata (PNG tEXt chunks or stealth alpha channel)
 * Supports PNG and WebP formats
 */
export async function parseNAIMetadata(imageData: ArrayBuffer | Uint8Array): Promise<NAIMetadata | null> {
    try {
        const bytes = imageData instanceof ArrayBuffer ? new Uint8Array(imageData) : imageData
        const imageType = detectImageType(bytes)

        let metadata: NAIMetadata | null = null

        if (imageType === 'image/png') {
            metadata = await extractTextChunkMetadata(bytes)
        } else if (imageType === 'image/webp') {
            metadata = extractWebpExifMetadata(bytes)
        }

        // If no metadata found yet, try stealth alpha channel (works for PNG/WebP)
        if (!metadata) {
            const imgData = await getImageData(bytes)
            if (imgData) {
                metadata = await extractStealthMetadata(imgData)
            }
        }

        return metadata
    } catch (error) {
        console.error('Failed to parse metadata:', error)
        return null
    }
}

/**
 * Extract NAI metadata from a WebP file's EXIF chunk.
 *
 * NAI v4+ stores a single JSON object in the EXIF chunk with the shape:
 *   { "Comment": "<nested JSON string>", "Description": "...", "Software": "NovelAI",
 *     "Source": "NovelAI Diffusion V4.5 XXXXX", "Title": "...", "Generation time": "..." }
 *
 * We locate the outer JSON by brace-balance (rather than parsing full EXIF/TIFF),
 * then feed the inner Comment JSON to convertNAIFormat.
 */
function extractWebpExifMetadata(bytes: Uint8Array): NAIMetadata | null {
    // RIFF header: "RIFF" <size:u32le> "WEBP"
    if (bytes.length < 12) return null
    if (bytes[0] !== 0x52 || bytes[1] !== 0x49 || bytes[2] !== 0x46 || bytes[3] !== 0x46) return null
    if (bytes[8] !== 0x57 || bytes[9] !== 0x45 || bytes[10] !== 0x42 || bytes[11] !== 0x50) return null

    const decoder = new TextDecoder('utf-8')
    let off = 12
    while (off + 8 <= bytes.length) {
        const fourcc = String.fromCharCode(bytes[off], bytes[off + 1], bytes[off + 2], bytes[off + 3])
        const size = bytes[off + 4] | (bytes[off + 5] << 8) | (bytes[off + 6] << 16) | (bytes[off + 7] << 24)
        const dataStart = off + 8
        const dataEnd = dataStart + size
        if (dataEnd > bytes.length) break

        if (fourcc === 'EXIF') {
            const exifText = decoder.decode(bytes.subarray(dataStart, dataEnd))
            // Locate the outer JSON object by finding the first '{' and balancing braces.
            const jsonStart = exifText.indexOf('{"Comment"')
            if (jsonStart >= 0) {
                let depth = 0
                let inString = false
                let escape = false
                let jsonEnd = -1
                for (let i = jsonStart; i < exifText.length; i++) {
                    const ch = exifText[i]
                    if (escape) { escape = false; continue }
                    if (ch === '\\') { escape = true; continue }
                    if (ch === '"') { inString = !inString; continue }
                    if (inString) continue
                    if (ch === '{') depth++
                    else if (ch === '}') {
                        depth--
                        if (depth === 0) { jsonEnd = i + 1; break }
                    }
                }
                if (jsonEnd > jsonStart) {
                    try {
                        const outer = JSON.parse(exifText.slice(jsonStart, jsonEnd))
                        if (typeof outer.Comment === 'string') {
                            const inner = JSON.parse(outer.Comment)
                            const metadata = convertNAIFormat(inner)
                            metadata.source = 'text_chunk'
                            if (typeof outer.Source === 'string') metadata.model = outer.Source
                            applyModelMetadata(metadata)
                            const modelKey = metadata.modelId ?? null
                            const inferred = inferNAIPresets(metadata.prompt, metadata.negativePrompt, modelKey)
                            if (metadata.qualityToggle === undefined && inferred.qualityToggle !== undefined) {
                                metadata.qualityToggle = inferred.qualityToggle
                            }
                            if (metadata.ucPreset === undefined && inferred.ucPreset !== undefined) {
                                metadata.ucPreset = inferred.ucPreset
                            }
                            return metadata
                        }
                    } catch (e) {
                        console.error('[WebP EXIF] JSON parse failed:', e)
                    }
                }
            }
        }

        // Chunks are padded to even byte boundary.
        off = dataEnd + (size & 1)
    }
    return null
}

/**
 * Extract metadata from PNG tEXt chunks
 */
async function extractTextChunkMetadata(bytes: Uint8Array): Promise<NAIMetadata | null> {
    let offset = 8
    let metadata: NAIMetadata | null = null
    let modelSource: string | null = null

    while (offset < bytes.length) {
        // Read chunk length (4 bytes, big-endian)
        const length = (bytes[offset] << 24) | (bytes[offset + 1] << 16) |
            (bytes[offset + 2] << 8) | bytes[offset + 3]
        offset += 4

        // Read chunk type (4 bytes)
        const type = String.fromCharCode(bytes[offset], bytes[offset + 1],
            bytes[offset + 2], bytes[offset + 3])
        offset += 4

        if (type === 'tEXt' || type === 'iTXt') {
            // Read chunk data
            const chunkData = bytes.slice(offset, offset + length)
            const textData = new TextDecoder('utf-8').decode(chunkData)

            // tEXt format: keyword\0value
            const nullIndex = textData.indexOf('\0')
            if (nullIndex !== -1) {
                const keyword = textData.slice(0, nullIndex)
                let value = textData.slice(nullIndex + 1)

                // iTXt has additional fields before the actual text
                if (type === 'iTXt') {
                    const parts = value.split('\0')
                    value = parts[parts.length - 1] || value
                }

                if (keyword === 'Comment' || keyword === 'parameters') {
                    try {
                        const parsed = JSON.parse(value)
                        metadata = convertNAIFormat(parsed)
                        metadata.source = 'text_chunk'
                    } catch {
                        metadata = parseA1111Format(value)
                        if (metadata) metadata.source = 'text_chunk'
                    }
                } else if (keyword === 'Source') {
                    // Store model source temporarily, will be added after metadata is created
                    modelSource = value
                }
            }
        }

        // Skip chunk data and CRC
        offset += length + 4

        // Stop at IEND
        if (type === 'IEND') break
    }

    // Add model source if found
    if (metadata && modelSource) {
        metadata.model = modelSource
    }

    // If this image was produced by NAIS2, trust our own nais2-params chunk
    // (qualityToggle / ucPreset / promptParts as we sent them) over any heuristic.
    const nais2 = metadata ? readNais2Params(bytes) : null
    if (metadata && nais2) {
        if (typeof nais2.qualityToggle === 'boolean') metadata.qualityToggle = nais2.qualityToggle
        if (typeof nais2.ucPreset === 'number') metadata.ucPreset = nais2.ucPreset
        if (nais2.promptParts && typeof nais2.promptParts === 'object') {
            const pp = nais2.promptParts
            metadata.promptParts = {
                base: pp.base ?? '',
                additional: pp.additional ?? '',
                detail: pp.detail ?? '',
                negative: pp.negative,
                inpainting: pp.inpainting,
            }
        }
        const generationSources = parseGenerationSources(nais2.generationSources)
        if (generationSources) metadata.generationSources = generationSources
    }

    // Heuristically recover qualityToggle / ucPreset from prompt/uc text only
    // when the nais2-params chunk did not supply them (images from NAI web,
    // third-party tools, etc.). NAI v4/v4.5 never embeds these flags in the
    // Comment JSON.
    if (metadata) {
        applyModelMetadata(metadata)
        const modelKey = metadata.modelId ?? null
        const inferred = inferNAIPresets(metadata.prompt, metadata.negativePrompt, modelKey)
        if (metadata.qualityToggle === undefined && inferred.qualityToggle !== undefined) {
            metadata.qualityToggle = inferred.qualityToggle
        }
        if (metadata.ucPreset === undefined && inferred.ucPreset !== undefined) {
            metadata.ucPreset = inferred.ucPreset
        }
    }

    return metadata
}

/**
 * NAI preset text tables (from official docs).
 * NAI embeds these into prompt/uc at generation time but does NOT write
 * qualityToggle/ucPreset into the PNG Comment JSON — they must be heuristically
 * recovered by matching the known texts.
 *
 * Source: https://docs.novelai.net/en/image/qualitytags
 *         https://docs.novelai.net/en/image/undesiredcontent
 */

// Core phrases the prompt must end with for qualityToggle=true.
// NAI may append a fuller variant (e.g. V4.5 Full prepends ", location, ..."),
// so we match only the stable trailing phrases. Multiple entries allow us to
// catch both canonical and shortened variants seen in real exports.
const QUALITY_TAG_SIGNATURES: Record<string, string[]> = Object.fromEntries(
    AVAILABLE_MODELS
        .map(model => [
            model.id,
            model.qualityTagPresets.map(preset => preset.suffix.replace(/^,\s*/, '')).filter(Boolean),
        ])
        .filter(([, signatures]) => signatures.length > 0),
)

const UC_PRESET_PREFIXES: Record<string, Partial<Record<number, string>>> = Object.fromEntries(
    AVAILABLE_MODELS.map(model => [
        model.id,
        Object.fromEntries(model.ucPresets.filter(preset => preset.prefix).map(preset => [preset.value, preset.prefix])),
    ]),
)

// Map Source metadata to the matching generation model.
function detectModelKey(source: string | null | undefined): string | null {
    if (!source) return null
    const normalized = source.toLowerCase()
    if (normalized.includes('v5')) return normalized.includes('curated')
        ? 'nai-diffusion-5-curated'
        : 'nai-diffusion-5-full'
    if (normalized.includes('v4.5')) return normalized.includes('curated')
        ? 'nai-diffusion-4-5-curated'
        : 'nai-diffusion-4-5-full'
    if (normalized.includes('v4')) return normalized.includes('curated')
        ? 'nai-diffusion-4-curated-preview'
        : 'nai-diffusion-4-full'
    if (normalized.includes('furry') && normalized.includes('v3')) return 'nai-diffusion-furry-3'
    if (normalized.includes('v3')) return 'nai-diffusion-3'
    return null
}

function applyModelMetadata(metadata: NAIMetadata) {
    const modelId = detectModelKey(metadata.model)
    if (!modelId) return

    metadata.modelId = modelId
    const raw = metadata.raw
    const qualityHint = raw?.tag_hint_qt
    if (typeof qualityHint === 'number') {
        const preset = getModelCapabilities(modelId).qualityTagPresets
            .find(option => option.tagHint === qualityHint)
        if (preset) {
            metadata.qualityTagPreset = preset.value
            metadata.qualityToggle = preset.value !== 'none'
        }
    }

    const ucHint = raw?.tag_hint_uc_preset
    if (typeof ucHint === 'number') {
        const preset = getModelCapabilities(modelId).ucPresets
            .find(option => option.tagHint === ucHint)
        if (preset) metadata.ucPreset = preset.value
    }
}

// Returns { qualityToggle, ucPreset } inferred from prompt/uc text.
// Only sets a field when a preset match is found.
function inferNAIPresets(
    prompt: string | undefined,
    uc: string | undefined,
    modelKey: string | null
): { qualityToggle?: boolean; ucPreset?: number } {
    const out: { qualityToggle?: boolean; ucPreset?: number } = {}

    // Quality Tags: check tail of prompt against known signatures.
    // Allow trailing comma/whitespace since real NAI exports often end with them.
    if (prompt) {
        const tail = prompt.trimEnd().replace(/[,\s]+$/, '')
        // Prefer model-matched signature; fall back to other known signatures.
        const keys = modelKey
            ? [modelKey, ...Object.keys(QUALITY_TAG_SIGNATURES).filter(k => k !== modelKey)]
            : Object.keys(QUALITY_TAG_SIGNATURES)
        outer: for (const k of keys) {
            for (const sig of QUALITY_TAG_SIGNATURES[k] || []) {
                if (tail.endsWith(sig)) { out.qualityToggle = true; break outer }
            }
        }
        if (out.qualityToggle === undefined && modelKey && QUALITY_TAG_SIGNATURES[modelKey]) {
            // Explicit false only when we had a model match and no signature hit.
            out.qualityToggle = false
        }
    }

    // UC Preset: look for preset prefix near the start of uc (allow short custom
    // prefix like "nsfw, " before the preset text — NAI web does the same).
    if (uc && modelKey && UC_PRESET_PREFIXES[modelKey]) {
        const table = UC_PRESET_PREFIXES[modelKey]
        // Sort keys by prefix length desc so longer / more-specific presets win
        // (Human Focus is a superset of Heavy on v4.5 Full).
        const orderedPresets = Object.entries(table)
            .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
            .sort(([, a], [, b]) => b.length - a.length)
        for (const [numStr, prefix] of orderedPresets) {
            const idx = uc.indexOf(prefix)
            if (idx >= 0 && idx <= 50) { out.ucPreset = Number(numStr); break }
        }
    }

    return out
}

/**
 * Convert NAI's internal format to our format
 */
function convertNAIFormat(data: Record<string, unknown>): NAIMetadata {
    const metadata: NAIMetadata = {
        raw: data
    }

    // Basic prompts
    if (data.prompt) metadata.prompt = String(data.prompt)

    // V4 negative prompt has higher priority than legacy 'uc'
    const v4NegPrompt = data.v4_negative_prompt as NAIMetadata['v4_negative_prompt'] | undefined
    if (v4NegPrompt?.caption?.base_caption) {
        metadata.negativePrompt = String(v4NegPrompt.caption.base_caption)
    } else if (data.uc) {
        metadata.negativePrompt = String(data.uc)
    } else if (data.negative_prompt) {
        metadata.negativePrompt = String(data.negative_prompt)
    } else if (data.undesired_content) {
        metadata.negativePrompt = String(data.undesired_content)
    }

    // Generation params
    if (data.steps) metadata.steps = Number(data.steps)
    if (data.scale) metadata.cfgScale = Number(data.scale)
    if (data.cfg_rescale !== undefined && data.cfg_rescale !== null) {
        metadata.cfgRescale = Number(data.cfg_rescale)
    }
    if (data.seed) metadata.seed = Number(data.seed)
    if (data.sampler) metadata.sampler = String(data.sampler)
    if (data.noise_schedule) metadata.scheduler = String(data.noise_schedule)

    // SMEA
    if (typeof data.sm === 'boolean') metadata.smea = data.sm
    if (typeof data.sm_dyn === 'boolean') metadata.smeaDyn = data.sm_dyn
    if (data.skip_cfg_above_sigma !== undefined && data.skip_cfg_above_sigma !== null) metadata.variety = true

    // NAI UI options — check camelCase, snake_case, and alternative names
    const rawQualityToggle =
        data.qualityToggle ??
        data.quality_toggle ??
        data.add_quality_tags ??
        data.addQualityTags
    if (typeof rawQualityToggle === 'boolean') metadata.qualityToggle = rawQualityToggle

    const rawUcPreset =
        data.ucPreset ??
        data.uc_preset ??
        data.undesired_content_preset ??
        data.undesiredContentPreset
    if (typeof rawUcPreset === 'number') metadata.ucPreset = rawUcPreset

    if (Object.prototype.hasOwnProperty.call(data, 'tag_hint_transparent_background')) {
        metadata.transparentBackground = data.tag_hint_transparent_background === true
    }

    // Resolution
    if (data.width) metadata.width = Number(data.width)
    if (data.height) metadata.height = Number(data.height)

    // V4 prompts (if available)
    if (data.v4_prompt) {
        metadata.v4_prompt = data.v4_prompt as NAIMetadata['v4_prompt']
    }
    if (data.v4_negative_prompt) {
        metadata.v4_negative_prompt = data.v4_negative_prompt as NAIMetadata['v4_negative_prompt']
    }

    // Reference images - Vibe Transfer
    if (data.reference_image_multiple && Array.isArray(data.reference_image_multiple) && data.reference_image_multiple.length > 0) {
        metadata.hasVibeTransfer = true
        metadata.encodedVibes = data.reference_image_multiple as string[]
    }
    if (data.reference_strength_multiple && Array.isArray(data.reference_strength_multiple) && data.reference_strength_multiple.length > 0) {
        metadata.hasVibeTransfer = true

        // Build detailed Vibe Transfer info
        const strengths = data.reference_strength_multiple as number[]
        const infoExtracted = (data.reference_information_extracted_multiple as number[]) || []

        metadata.vibeTransferInfo = strengths.map((strength, i) => ({
            strength,
            informationExtracted: infoExtracted[i] ?? 1.0
        }))
    }

    // Character Reference (director tools)
    if (data.director_reference_strengths && Array.isArray(data.director_reference_strengths) && (data.director_reference_strengths as unknown[]).length > 0) {
        metadata.hasCharacterReference = true

        const strengths = data.director_reference_strengths as number[]
        const secondary = (data.director_reference_secondary_strengths as number[]) || []

        metadata.characterReferenceInfo = strengths.map((strength, i) => ({
            strength,
            informationExtracted: secondary[i] ?? 1.0
        }))
    }

    return metadata
}

/**
 * Parse A1111 format (Stable Diffusion WebUI format)
 * Format: prompt\nNegative prompt: neg\nSteps: X, Sampler: Y, ...
 */
function parseA1111Format(text: string): NAIMetadata | null {
    const lines = text.split('\n')
    if (lines.length < 2) return null

    const metadata: NAIMetadata = {}

    let negativeStart = -1
    let paramsStart = -1

    for (let i = 0; i < lines.length; i++) {
        if (lines[i].startsWith('Negative prompt:')) {
            negativeStart = i
        } else if (lines[i].match(/^Steps:/)) {
            paramsStart = i
            break
        }
    }

    if (negativeStart === -1 && paramsStart === -1) return null

    // Extract prompt
    const promptEnd = negativeStart !== -1 ? negativeStart : paramsStart
    if (promptEnd > 0) {
        metadata.prompt = lines.slice(0, promptEnd).join('\n')
    }

    // Extract negative prompt
    if (negativeStart !== -1 && paramsStart !== -1) {
        const negLines = lines.slice(negativeStart, paramsStart)
        negLines[0] = negLines[0].replace('Negative prompt: ', '')
        metadata.negativePrompt = negLines.join('\n')
    }

    // Parse params line
    if (paramsStart !== -1) {
        const paramsLine = lines[paramsStart]
        const params = paramsLine.split(', ')

        for (const param of params) {
            const [key, value] = param.split(': ')
            if (!key || !value) continue

            switch (key.trim()) {
                case 'Steps':
                    metadata.steps = parseInt(value)
                    break
                case 'Sampler':
                    metadata.sampler = value
                    break
                case 'CFG scale':
                    metadata.cfgScale = parseFloat(value)
                    break
                case 'Seed':
                    metadata.seed = parseInt(value)
                    break
                case 'Size':
                    const [w, h] = value.split('x')
                    metadata.width = parseInt(w)
                    metadata.height = parseInt(h)
                    break
            }
        }
    }

    return metadata
}

/**
 * Parse metadata from a File object
 */
export async function parseMetadataFromFile(file: File): Promise<NAIMetadata | null> {
    const buffer = await file.arrayBuffer()
    return parseNAIMetadata(buffer)
}

/**
 * Parse metadata from a base64 string
 */
export async function parseMetadataFromBase64(base64: string): Promise<NAIMetadata | null> {
    // Remove data URL prefix if present
    const base64Data = base64.replace(/^data:image\/\w+;base64,/, '')

    // Convert base64 to ArrayBuffer
    const binaryString = atob(base64Data)
    const bytes = new Uint8Array(binaryString.length)
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i)
    }

    return parseNAIMetadata(bytes)
}
